-- ============================================================================
-- PicoOracle Agent — Oracle SQL DDL
-- 三层记忆架构：表意识 / 个人深藏潜意识 / 集体潜意识
-- Oracle ADB lake5, 384-dim 向量检索, AES-256-GCM 加密
-- ============================================================================

-- ── 表意识：session 级工作记忆（ADK-Go session 后端）──
CREATE TABLE PICO_SESSION (
  APP_NAME      VARCHAR2(256)  NOT NULL,
  USER_ID       VARCHAR2(256)  NOT NULL,
  SESSION_ID    VARCHAR2(256)  NOT NULL,
  STATE_JSON    CLOB,
  EVENTS_JSON   CLOB,
  CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_PICO_SESSION PRIMARY KEY (APP_NAME, USER_ID, SESSION_ID)
);

-- ── 个人深藏潜意识：博弈级记忆（数十到数百条），AES-256-GCM 加密，向量检索 ──
CREATE TABLE PICO_MEMORY_DEEP (
  ID            RAW(16) DEFAULT SYS_GUID() NOT NULL,
  AGENT_NAME    VARCHAR2(128)  NOT NULL,
  LAYER         VARCHAR2(64) DEFAULT 'deep',
  CONTENT_ENCRYPTED  BLOB,
  IV_SALT       RAW(24),       -- 12-byte IV + 12-byte salt for AES-256-GCM
  EMBEDDING     RAW(1536),     -- 384 dims x 4 bytes (FLOAT32)
  VECTOR_DIST   BINARY_FLOAT,  -- 暂存，由 ORDS/DBMS_VECTOR 填充
  METADATA_JSON CLOB,
  CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_PICO_MEMORY_DEEP PRIMARY KEY (ID)
);

-- ── 集体潜意识：原型级记忆（所有 agent 可读），向量检索，不加密 ──
CREATE TABLE PICO_MEMORY_SHARED (
  ID            RAW(16) DEFAULT SYS_GUID() NOT NULL,
  AGENT_NAME    VARCHAR2(128),              -- 来源 agent（可选）
  LAYER         VARCHAR2(64) DEFAULT 'shared',
  CONTENT_PLAINTEXT CLOB,
  EMBEDDING     RAW(1536),
  VECTOR_DIST   BINARY_FLOAT,
  METADATA_JSON CLOB,
  CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_PICO_MEMORY_SHARED PRIMARY KEY (ID)
);

-- ── 索引 ──
CREATE INDEX IDX_PICO_SESSION_APP_USER ON PICO_SESSION (APP_NAME, USER_ID);
CREATE INDEX IDX_PICO_MEMORY_DEEP_AGENT ON PICO_MEMORY_DEEP (AGENT_NAME);
CREATE INDEX IDX_PICO_MEMORY_DEEP_LAYER ON PICO_MEMORY_DEEP (LAYER);
CREATE INDEX IDX_PICO_MEMORY_SHARED_LAYER ON PICO_MEMORY_SHARED (LAYER);
CREATE INDEX IDX_PICO_MEMORY_DEEP_TIME ON PICO_MEMORY_DEEP (CREATED_AT);
CREATE INDEX IDX_PICO_MEMORY_SHARED_TIME ON PICO_MEMORY_SHARED (CREATED_AT);

-- ── Oracle Vector Search：embedding 列的向量索引 ──
CREATE VECTOR INDEX IDX_PICO_DEEP_VECT ON PICO_MEMORY_DEEP (EMBEDDING) 
  ORGANIZATION AUTO;
CREATE VECTOR INDEX IDX_PICO_SHARED_VECT ON PICO_MEMORY_SHARED (EMBEDDING) 
  ORGANIZATION AUTO;

-- ── 序列号：用于批量任务追踪 ──
CREATE SEQUENCE SEQ_PICO_TXN START WITH 1 INCREMENT BY 1;
