// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package auth

import (
	"context"
	"fmt"
	"os"
	"strings"

	"golang.org/x/oauth2/clientcredentials"
)

// AuthentikConfig defines credentials for Authentik M2M / Agent-to-Agent authentication.
type AuthentikConfig struct {
	BaseURL      string   // e.g. "https://authentik.capitaltrain.cn"
	Slug         string   // Application or Provider Slug, defaults to "default-provider" if empty
	ClientID     string   // OAuth2 Client ID generated by Terraform
	ClientSecret string   // OAuth2 Client Secret
	Scopes       []string // Optional OAuth2 scopes (defaults to "openid", "profile")
}

// AuthentikClientCredentials returns a CredentialProvider for Authentik M2M / A-to-A authentication
// using 2-legged OAuth2 Client Credentials Grant.
func AuthentikClientCredentials(cfg AuthentikConfig) CredentialProvider {
	return ProviderFunc(func(ctx context.Context) (Credential, error) {
		if cfg.BaseURL == "" {
			return nil, fmt.Errorf("auth: missing authentik base_url")
		}
		if cfg.ClientID == "" || cfg.ClientSecret == "" {
			return nil, fmt.Errorf("auth: missing authentik client_id or client_secret")
		}

		slug := cfg.Slug
		if slug == "" {
			slug = "default-provider"
		}

		scopes := cfg.Scopes
		if len(scopes) == 0 {
			scopes = []string{"openid", "profile"}
		}

		tokenURL := fmt.Sprintf("%s/application/o/%s/token/", strings.TrimSuffix(cfg.BaseURL, "/"), slug)

		ccConfig := &clientcredentials.Config{
			ClientID:     cfg.ClientID,
			ClientSecret: cfg.ClientSecret,
			TokenURL:     tokenURL,
			Scopes:       scopes,
		}

		return OAuth2Credential{TokenSource: ccConfig.TokenSource(ctx)}, nil
	})
}

// AuthentikFromEnv returns a CredentialProvider auto-discovered from environment variables:
// - AUTHENTIK_URL
// - AUTHENTIK_CLIENT_ID
// - AUTHENTIK_CLIENT_SECRET
// - AUTHENTIK_SLUG (optional)
func AuthentikFromEnv() (CredentialProvider, error) {
	url := os.Getenv("AUTHENTIK_URL")
	clientID := os.Getenv("AUTHENTIK_CLIENT_ID")
	clientSecret := os.Getenv("AUTHENTIK_CLIENT_SECRET")
	slug := os.Getenv("AUTHENTIK_SLUG")

	if url == "" || clientID == "" || clientSecret == "" {
		return nil, fmt.Errorf("auth: missing one or more env vars (AUTHENTIK_URL, AUTHENTIK_CLIENT_ID, AUTHENTIK_CLIENT_SECRET)")
	}

	return AuthentikClientCredentials(AuthentikConfig{
		BaseURL:      url,
		Slug:         slug,
		ClientID:     clientID,
		ClientSecret: clientSecret,
	}), nil
}
